image: python:3.9

before_script:
  - python -V
  - pip install jupyter-book

pages:
  stage: deploy
  script:
    - jupyter-book build .
    - mkdir .public
    - cp -r _build/html/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main