# The Docker image that will be used to build your app
image: python:3.9

before_script:
  - python -V  # Print python version for logs
  - pip install jupyter-book

pages:
  script:
    - jupyter-book build .
    - mv _build/html public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH