title: Computational Essays
author: <a href="https://www.geschichte.hu-berlin.de/de/bereiche-und-lehrstuehle/digital-history">Digital History, Humboldt-Universität zu Berlin</a>
copyright: "2024"
language: de
logo: img/Logo_DigitalHistoryBerlin.png

url: https://digital-history-berlin.github.io/
baseurl: /computational-essays

# HTML-specific settings
html:
  comments:
    hypothesis: true
  extra_navbar: |
    <div>
    Veröffentlicht durch Digital History Lehrstuhl, Humboldt-Universität zu Berlin
    </div>
  extra_footer: |
    <div>
    <a href="http://creativecommons.org/licenses/by/4.0/"><img class="license" alt="Creative Commons License" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> This book is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons BY 4.0 License</a>.
    </div>

# Execution settings
execute:
  execute_notebooks: auto
  timeout: 300
  allow_errors: false

# LaTeX settings
latex:
  latex_documents:
    targetname: book.tex

# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  thebe: true
  colab: false
  binderhub_url: ""

parse:
  myst_enable_extensions:
    # These are the default extensions
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    # Add mermaid support
    - mermaid
 
# Search settings
sphinx:
  config:
    html_show_copyright: false
    language: de
    myst_nb_output_stderr: show
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.1.3/mermaid.min.js